<?php

/**
 * Implements hook_requirements().
 */
function openai_requirements($phase) {
  $requirements = array();

  if ($phase == 'runtime') {
    $config = config_get('openai.settings');

    if (!empty($config['api_key'])) {
      $requirements['openai'] = array(
        'title' => t('OpenAI'),
        'value' => t('API key detected'),
        'severity' => REQUIREMENT_OK,
      );
    }
    else {
      $message = t('You have not provided an OpenAI API key yet. This is required for its functionality to work. Please obtain an API key from <a href=":account">your OpenAI account</a> and add it to the <a href=":settings">OpenAI settings configuration here</a>.',
        array(
          ':account' => 'https://platform.openai.com/',
          ':settings' => url('admin/config/openai/settings')
        )
      );

      $requirements['openai'] = array(
        'title' => t('OpenAI'),
        'value' => t('API key not provided'),
        'severity' => REQUIREMENT_ERROR,
        'description' => $message,
      );
    }
  }

  return $requirements;
}

/**
 * Implements hook_uninstall().
 */
function openai_uninstall() {
  // Delete configuration on uninstall.
  config('openai.settings')->delete();
}
