<?php

/**
 * Implements hook_schema().
 */
function openai_dblog_schema() {
  $schema['openai_dblog'] = [
    'description' => 'Stores OpenAI responses returned for log messages.',
    'fields'      => [
      'id'          => [
        'type'        => 'serial',
        'not null'    => TRUE,
        'description' => 'The openai_dblog record ID.',
      ],
      'hash'        => [
        'type'        => 'varchar',
        'length'      => 256,
        'not null'    => TRUE,
        'description' => 'Hash value of the original log message for comparison.',
      ],
      'message'     => [
        'type'        => 'text',
        'not null'    => TRUE,
        'description' => 'Text of log message to be passed into the t() function.',
      ],
      'explanation' => [
        'type'        => 'text',
        'not null'    => TRUE,
        'description' => 'Text of OpenAI explanation returned.',
      ],
    ],
    'primary key' => ['id'],
    'unique keys' => [
      'hash' => ['hash'],
    ],
  ];

  return $schema;
}

/**
 * Implements hook_uninstall().
 */
function openai_dblog_uninstall() {
  // Delete the configuration.
  config_clear('openai_dblog.settings', 'levels');
  config_clear('openai_dblog.settings', 'model');
  // Drop the database table.
  db_drop_table('openai_dblog');
}

