<?php

/**
 * @file
 * Contains hook implementations for this module.
 */

use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\HtmlCommand;
use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeInterface;
use Drupal\Component\Utility\Unicode;
use Drupal\openai\Utility\StringHelper;

/**
 * Implements hook_form_alter().
 */
function openai_content_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  $account = \Drupal::currentUser();

  if (preg_match('/node_(add|.*_edit)_form/', $form_id) && $account->hasPermission('access openai content tools')) {
    $form['openai_tone_edit'] = [
      '#type' => 'details',
      '#title' => t('Adjust content tone'),
      '#group' => 'advanced',
      '#tree' => TRUE,
    ];

    $form['openai_tone_edit']['message'] = [
      '#markup' => t('Have OpenAI check your content and adjust the tone of it for different reader audiences for you.'),
    ];

    // @todo: these values should be configurable options
    $form['openai_tone_edit']['tone'] = [
      '#type' => 'select',
      '#title' => t('Choose tone'),
      '#description' => t('Selecting one of the options will adjust/reword the body content to be appropriate for the target audience.'),
      '#options' => [
        'friendly' => t('Friendly'),
        'professional' => t('Professional'),
        'helpful' => t('Helpful'),
        'easier for a high school educated reader' => t('High school level reader'),
        'easier for a college educated reader' => t('College level reader'),
        'explained to a five year old' => t('Explain like I\'m 5'),
      ],
    ];

    $form['openai_tone_edit']['response'] = [
      '#prefix' => '<br /><div id="openai-tone-edit-response">',
      '#suffix' => '</div>',
    ];

    $form['openai_tone_edit']['edit'] = [
      '#type' => 'button',
      '#value' => t('Adjust tone'),
      '#limit_validation_errors' => [],
      '#ajax' => [
        'callback' => 'openai_content_node_adjust_tone',
        'wrapper' => 'openai-tone-edit-response',
      ],
    ];

    $form['openai_summarize'] = [
      '#type' => 'details',
      '#title' => t('Summarize text'),
      '#group' => 'advanced',
    ];

    $form['openai_summarize']['response'] = [
      '#type' => 'markup',
      '#markup' => t('This will use the node body field and OpenAI will attempt to summarize it for you. You can use the result to help generate a summary/teaser, social media share text, or similar.'),
      '#prefix' => '<div id="openai-summarize-response">',
      '#suffix' => '</div>',
    ];

    $form['openai_summarize']['do_summarize'] = [
      '#type' => 'button',
      '#value' => t('Summarize'),
      '#limit_validation_errors' => [],
      '#ajax' => [
        'callback' => 'openai_content_node_field_summarize',
        'wrapper' => 'openai-summarize-response',
      ],
    ];

    $form['openai_suggest'] = [
      '#type' => 'details',
      '#title' => t('Suggest taxonomy'),
      '#group' => 'advanced',
    ];

    $form['openai_suggest']['response'] = [
      '#type' => 'markup',
      '#markup' => t('OpenAI can attempt to suggest possible classification terms to use as taxonomy.'),
      '#prefix' => '<div id="openai-suggest-response">',
      '#suffix' => '</div>',
    ];

    $form['openai_suggest']['do_suggest'] = [
      '#type' => 'button',
      '#value' => t('Suggest taxonomy'),
      '#limit_validation_errors' => [],
      '#ajax' => [
        'callback' => 'openai_content_node_suggest_taxonomy',
        'wrapper' => 'openai-suggest-response',
      ],
    ];
  }
}

/**
 * The AJAX callback for adjusting the tone of body content.
 *
 * @param array $form
 *   The node form.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state.
 *
 * @return \Drupal\Core\Ajax\AjaxResponse
 *   The HTML response.
 */
function openai_content_node_adjust_tone(array &$form, FormStateInterface $form_state) {
  $body = $form_state->getValue('body')[0]['value'];
  $tone = $form_state->getValue('openai_tone_edit')['tone'];

  if (!empty($body)) {
    $client = \Drupal::service('openai.client');
    $body = StringHelper::prepareText($body, [], 3900);

    $response = $client->completions()->create(
      [
        'model' => 'text-davinci-003',
        'prompt' => 'Change the tone of the following text to be more ' . $tone . ':\r\n"' . $body . '"',
        'temperature' => 0.7,
        'max_tokens' => 2048,
      ],
    );

    $result = $response->toArray();
    $text = trim($result["choices"][0]["text"]) ?? t('No result could be generated.');
  } else {
    $text = t('The body field has no text. Please supply content to the body field.');
  }

  $response = new AjaxResponse();
  $response->addCommand(new HtmlCommand('#openai-tone-edit-response', $text));
  return $response;
}

/**
 * The AJAX callback for summarizing a field.
 *
 * @param array $form
 *   The node form.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state.
 *
 * @return \Drupal\Core\Ajax\AjaxResponse
 *   The HTML response.
 */
function openai_content_node_field_summarize(array &$form, FormStateInterface $form_state) {
  $body = $form_state->getValue('body')[0]['value'];

  if (!empty($body)) {
    $client = \Drupal::service('openai.client');
    $body = StringHelper::prepareText($body, [], 3900);

    $response = $client->completions()->create(
      [
        'model' => 'text-davinci-003',
        'prompt' => 'Create a detailed summary of the following text in less than 130 words:\r\n"' . $body . '"',
        'temperature' => 0.7,
        'max_tokens' => 2048,
      ],
    );

    $result = $response->toArray();
    $text = trim($result["choices"][0]["text"]) ?? t('No result could be generated.');
  } else {
    $text = t('The body field has no text. Please supply content to the body field.');
  }

  $response = new AjaxResponse();
  $response->addCommand(new HtmlCommand('#openai-summarize-response', $text));
  return $response;
}

/**
 * The AJAX callback for suggesting taxonomy.
 *
 * @param array $form
 *   The node form.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state.
 *
 * @return \Drupal\Core\Ajax\AjaxResponse
 *   The HTML response.
 */
function openai_content_node_suggest_taxonomy(array &$form, FormStateInterface $form_state) {
  $body = $form_state->getValue('body')[0]['value'];

  if (!empty($body)) {
    $client = \Drupal::service('openai.client');
    $body = StringHelper::prepareText($body, [], 3900);

    $response = $client->completions()->create(
      [
        'model' => 'text-davinci-003',
        'prompt' => 'Suggest five words to classify the following text. The words must be nouns or adjectives in a comma delimited list:\r\n"' . $body . '"',
        'temperature' => 0.4,
        'max_tokens' => 2048,
      ],
    );

    $result = $response->toArray();
    $text = trim($result["choices"][0]["text"]) ?? t('No terms could be generated from the provided input.');
  } else {
    $text = t('The body field has no text. Please supply content to the body field.');
  }

  $response = new AjaxResponse();
  $response->addCommand(new HtmlCommand('#openai-suggest-response', $text));
  return $response;
}
